const city=[
    { "id": 1, "city": "北京" },
    { "id": 2, "city": "天津" },
    { "id": 3, "city": "河北" },
    { "id": 4, "city": "山西" },
    { "id": 5, "city": "内蒙古" },
    { "id": 6, "city": "辽宁" },
    { "id": 7, "city": "吉林" },
    { "id": 8, "city": "黑龙江" },
    { "id": 9, "city": "上海" },
    { "id": 10, "city": "江苏" },
    { "id": 11, "city": "浙江" },
    { "id": 12, "city": "安徽" },
    { "id": 13, "city": "福建" },
    { "id": 14, "city": "江西" },
    { "id": 15, "city": "山东" },
    { "id": 16, "city": "河南" },
    { "id": 17, "city": "湖北" },
    { "id": 18, "city": "湖南" },
    { "id": 19, "city": "广东" },
    { "id": 20, "city": "广西" },
    { "id": 21, "city": "海南" },
    { "id": 22, "city": "重庆" },
    { "id": 23, "city": "四川" },
    { "id": 24, "city": "贵州" },
    { "id": 25, "city": "云南" },
    { "id": 26, "city": "西藏" },
    { "id": 27, "city": "陕西" },
    { "id": 28, "city": "甘肃" },
    { "id": 29, "city": "青海" },
    { "id": 30, "city": "宁夏" },
    { "id": 31, "city": "新疆" }
  ]
  export default city