export const GridEvent = {
  synchronize: 'synchronize',
  layoutStart: 'layoutStart',
  layoutEnd: 'layoutEnd',
  layoutAbort: 'layoutAbort',
  add: 'add',
  remove: 'remove',
  showStart: 'showStart',
  showEnd: 'showEnd',
  hideStart: 'hideStart',
  hideEnd: 'hideEnd',
  filter: 'filter',
  sort: 'sort',
  move: 'move',
  send: 'send',
  beforeSend: 'beforeSend',
  receive: 'receive',
  beforeReceive: 'beforeReceive',
  dragInit: 'dragInit',
  dragStart: 'dragStart',
  dragMove: 'dragMove',
  dragScroll: 'dragScroll',
  dragEnd: 'dragEnd',
  dragReleaseStart: 'dragReleaseStart',
  dragReleaseEnd: 'dragReleaseEnd',
  destroy: 'destroy'
}
