
export default [
  {
    title:'官网',
    url:'https://www.apps.vip',
    logo:"/icons/logo128.png"
  },
  {
    title:'元社区',
    url:'https://s.apps.vip',
    logo:"/icons/logo128.png"
  },
  {
    title:'京东',
    url:'https://www.jd.com',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/1_hc-L4OF-T8H7-l39B'
  },
  {
    title:'Bilibili',
    url:'https://www.bilibili.com',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/Y-Uo-cJa1-jL5N-IPtL'
  },
  {
    title:'知乎',
    url:'https://www.zhihu.com',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/VJPp-YaUC-DJ5z-7CYK'
  },
  {
    title:'抖音',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/1dFZ-0VRv-uit8-62IR',
    url:'https://www.douyin.com'
  },
  {
    title:'优酷',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/vk7N-wzvs-Xb77-WJKf',
    url:'https://www.youku.com'
  },
  {
    title:'腾讯视频',
    logo:'https://v.qq.com/favicon.ico',
    url:'https://v.qq.com/'
  },
  {
    title:'爱奇艺',
    logo:'https://up.apps.vip/yyscIcon/iqy.png',
    url:'https://www.iqiyi.com/'
  },
  {
    title:'淘宝',
    logo:'https://jxxt-1257689580.cos.ap-chengdu.myqcloud.com/GK3C-skR8-9wpd-ueqY',
    url:'https://www.taobao.com'
  }
]
