export const courierDetailList = [
  {
    goodName: "《悲惨世界》图书",
    time: "2023年10月23日 19:23",
    summary: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
    id: "100223233366223",
    shipWay: "顺丰快递",
    orderID: "SF00003618100",
    status: "collect",
    icon: "fluent-emoji:blue-book",
    flowDetail: [
      {
        title: "已揽收",
        time: "2023年10月22日 19:23",
        content: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
        status: "0",
      },
    ],
  },
  {
    goodName: "IKEA宜家沙发",
    time: "2023年10月22日 19:23",
    summary:
      "快件在「浙江陆运枢纽杭州」完成分拣，准备发往「嘉兴中通分拨」，根据规划班次预计发出时间「10月23日…",
    id: "100223233366225",
    shipWay: "中通快递",
    status: "enRoute",
    orderID: "SF00003618100",
    icon: "fluent-emoji:couch-and-lamp",
    flowDetail: [
      {
        title: "运输中",
        time: "2023年10月22日 19:23",
        content:
          "快件在「浙江陆运枢纽杭州」完成分拣，准备发往「嘉兴中通分拨」，根据规划班次预计发出时间「10月23日凌晨」",
        status: "0",
      },
      {
        time: "2023年10月22日 19:23",
        content: "快件到达【威海】,上一站是【青州分拨中心】",
      },
      {
        title: "已揽收",
        time: "2023年10月22日 19:23",
        content: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
        status: "0",
      },
    ],
  },
  {
    goodName: "YSL口红",
    time: "2023年10月22日 19:23",
    summary: "快件在【北京分拨中心】装车,正发往【青州分拨中心】",
    id: "10022323336620",
    shipWay: "韵达快递",
    orderID: "SF00003618100",
    status: "enRoute",
    icon: "fluent-emoji:lipstick",
    flowDetail: [
      {
        title: "运输中",
        time: "2023年10月22日 19:23",
        content:
          "快件在「浙江陆运枢纽杭州」完成分拣，准备发往「嘉兴中通分拨」，根据规划班次预计发出时间「10月23日凌晨」",
        status: "0",
      },
      {
        time: "2023年10月22日 19:23",
        content: "快件到达【威海】,上一站是【青州分拨中心】",
      },
      {
        title: "已揽收",
        time: "2023年10月22日 19:23",
        content: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
        status: "0",
      },
    ],
  },
  {
    goodName: "SONY XM5 头戴式耳机",
    time: "2023年10月22日 19:23",
    summary: "【威海】的【王奕凯】正在派件",
    id: "10022323336621",
    orderID: "SF00003618100",
    shipWay: "中通快递",
    status: "delivery",
    icon: "fluent-emoji:headphone",
    flowDetail: [
      {
        title: "派送中",
        time: "2023年10月22日 19:23",
        content: "【威海】的【王奕凯】正在派件",
        status: "0",
      },
      {
        title: "运输中",
        time: "2023年10月22日 19:23",
        content:
          "快件在「浙江陆运枢纽杭州」完成分拣，准备发往「嘉兴中通分拨」，根据规划班次预计发出时间「10月23日凌晨」",
        status: "0",
      },
      {
        time: "2023年10月22日 19:23",
        content: "快件到达【威海】,上一站是【青州分拨中心】",
      },
      {
        title: "已揽收",
        time: "2023年10月22日 19:23",
        content: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
        status: "0",
      },
    ],
  },
  {
    goodName: "SF00003618100",
    time: "2023年10月22日 19:23",
    summary:
      "您的快件已签收，如有疑问请电联系「王海，电话156788888888」，感谢您使用顺丰，期待再次为您服务。（主单总件数：1件）",
    id: "10022323336600",
    orderID: "SF00003618100",
    shipWay: "顺丰快递",
    status: "signed",
    icon: "fluent-emoji:package",
    flowDetail: [
      {
        title: "已签收",
        type: "sign",
        time: "2023年10月22日 19:23",
        content:
          "您的快件已签收，如有疑问请电联系「王海，电话156788888888」，感谢您使用顺丰，期待再次为您服务。（主单总件数：1件）",
        status: "0",
      },
      {
        title: "派送中",
        time: "2023年10月22日 19:23",
        content: "【威海】的【王奕凯】正在派件",
        status: "0",
      },
      {
        title: "运输中",
        time: "2023年10月22日 19:23",
        content:
          "快件在「浙江陆运枢纽杭州」完成分拣，准备发往「嘉兴中通分拨」，根据规划班次预计发出时间「10月23日凌晨」",
        status: "0",
      },
      {
        title: "",
        time: "2023年10月22日 19:23",
        content: "快件到达【威海】,上一站是【青州分拨中心】",
      },
      {
        title: "已揽收",
        time: "2023年10月22日 19:23",
        content: "快件在【北京环铁站】装车,正发往【北京分拨中心】",
        status: "0",
      },
    ],
  },
];

export const courierType = [
  { title: "全部", name: "all" },
  { title: "已揽收", name: "collect", color: "rgba(67,202,222,1)" },
  { title: "在途中", name: "enRoute", color: "var(--active-bg)" },
  { title: "派送中", name: "delivery", color: "var(--warning)" },
  { title: "已签收", name: "signed", color: "var(--success)" },
];

export const commonExpress = [
  { code: "SF", name: "顺丰速运" },
  { code: "JD", name: "京东快递" },
  { code: "ZTO", name: "中通快递" },
  { code: "YTO", name: "圆通速递" },
  { code: "YD", name: "	韵达速递" },
  { code: "STO", name: "申通快递" },
  { code: "YZPY", name: "邮政快递包裹" },
  { code: "EMS", name: "EMS" },
  { code: "HTKY", name: "百世快递" },
  { code: "DBL", name: "德邦快递" },
];

export const expressList = [
  { name: "百世快递", code: "HTKY" },
  { name: "中通快递", code: "ZTO" },
  { name: "申通快递", code: "STO" },
  { name: "圆通速递", code: "YTO" },
  { name: "韵达速递", code: "YD" },
  { name: "邮政快递包裹", code: "YZPY" },
  { name: "EMS", code: "EMS" },
  { name: "顺丰速运", code: "SF" },
  { name: "京东快递", code: "JD" },
  { name: "优速快递", code: "UC" },
  { name: "德邦快递", code: "DBL" },
  { name: "极兔速递", code: "JTSD" },
  { name: "菜鸟直送", code: "CNSD" },
  { name: "菜鸟橙运", code: "CNCY" },
  { name: "宅急送", code: "ZJS" },
  { name: "丰网速运", code: "FWX" },
  { name: "安能快递", code: "ANE" },
  { name: "安能快运/物流", code: "ANEKY" },
  { name: "安捷快递", code: "AJ" },
  { name: "安迅物流", code: "AX" },
  { name: "安邮美国", code: "AYUS" },
  { name: "亚马逊物流", code: "AMAZON" },
  { name: "澳门邮政", code: "AOMENYZ" },
  { name: "澳多多", code: "ADD" },
  { name: "澳邮专线", code: "AYCA" },
  { name: "安鲜达", code: "AXD" },
  { name: "安敏物流?", code: "ANMIN56?" },
  { name: "安得物流", code: "ANNTO" },
  { name: "澳德物流", code: "AUODEXPRESS" },
  { name: "转运四方", code: "A4PX" },
  { name: "A2U速递", code: "A2U" },
  { name: "AAE全球专递", code: "AAE" },
  { name: "明大快递", code: "ADAEXPRESS" },
  { name: "德国雄鹰速递", code: "ADLERLOGI" },
  { name: "安达信", code: "ADVANCING" },
  { name: "全程快递", code: "AGOPOST" },
  { name: "德方物流", code: "AHDF" },
  { name: "卡邦配送", code: "AHKBPS" },
  { name: "加拿大民航快递", code: "AIRGTC" },
  { name: "捷记方舟", code: "AJEXPRESS" },
  { name: "AlfaTrex", code: "ALFATREX" },
  { name: "无忧物流", code: "ALIEXPRESS" },
  { name: "ALLIED", code: "ALLIEDEXPRESS" },
  { name: "心怡物流", code: "ALOG" },
  { name: "亚马逊中国订单", code: "AMAZONCNORDER" },
  { name: "amazon-国际订单", code: "AMUSORDER" },
  { name: "安家同城快运", code: "ANJIATONGCHENG" },
  { name: "青岛安捷快递", code: "ANJIEKUAIDI" },
  { name: "Anteraja", code: "ANTERAJA" },
  { name: "荷属安的列斯荷兰邮政", code: "ANTILLESPOST" },
  { name: "安信达", code: "ANXINDAKUAIXI" },
  { name: "澳速物流", code: "AOSU" },
  { name: "Aramex", code: "ARAMEX" },
  { name: "ARC", code: "ARC" },
  { name: "澳达国际物流", code: "AUADEXPRESS" },
  { name: "澳货通", code: "AUEX" },
  { name: "奥地利邮政", code: "AUSTRIAPOST" },
  { name: "AUV国际快递", code: "AUVEXPRESS" },
  { name: "澳新物流", code: "AXEXPRESS" },
  { name: "安鹿物流", code: "ALWL" },
  { name: "八达通", code: "BDT" },
  { name: "百腾物流", code: "BETWL" },
  { name: "奔腾物流", code: "BNTWL" },
  { name: "八方安运", code: "BFAY" },
  { name: "百世国际", code: "BAISHIGUOJI" },
  { name: "百世云配", code: "BAISHIYP" },
  { name: "宝通快递", code: "BAOTONGKD" },
  { name: "8+1物流", code: "BJY" },
  { name: "报通快递", code: "BAOXIANDA" },
  { name: "BDC快递", code: "BDCGCC" },
  { name: "北京丰越供应链", code: "BEIJINGFENGYUE" },
  { name: "飛斯特", code: "BESTER" },
  { name: "败欧洲", code: "BEUROPE" },
  { name: "百福东方物流", code: "BFDF" },
  { name: "上海缤纷物流", code: "BFLG" },
  { name: "彪记快递", code: "BIAOJIKUAIDI" },
  { name: "青云物流", code: "BJQYWL" },
  { name: "鑫锐达", code: "BJXSRD" },
  { name: "远通盛源", code: "BJYTSYWL" },
  { name: "佰乐捷通", code: "BLJT56" },
  { name: "比利时邮政", code: "BLSYZ" },
  { name: "蓝天国际航空快递", code: "BLUESKYEXPRESS" },
  { name: "巴伦支快递", code: "BLZ" },
  { name: "标杆物流", code: "BMLCHINA" },
  { name: "笨鸟国际", code: "BN" },
  { name: "堡昕德速递", code: "BOSIND" },
  { name: "速方(Sufast)", code: "BPHCHINA" },
  { name: "百千诚物流", code: "BQCWL" },
  { name: "宏桥国际物流", code: "BRIEMS" },
  { name: "百事亨通速递", code: "BSHT" },
  { name: "邦泰快运", code: "BTEXPRESS" },
  { name: "展勤快递", code: "BYHT" },
  { name: "百世快运", code: "BTWL" },
  { name: "帮帮发转运", code: "BBFZY" },
  { name: "百城通物流", code: "BCTWL" },
  { name: "百米快运", code: "BAIMI" },
  { name: "北京渡石", code: "DS" },
  { name: "重庆博卡联物流?", code: "BKL?" },
  { name: "春风物流", code: "CFWL" },
  { name: "菜鸟橙运", code: "CNCY" },
  { name: "广东诚通物流", code: "CHTWL" },
  { name: "传喜物流", code: "CXHY" },
  { name: "城市100", code: "CITY100" },
  { name: "CEVA物流", code: "CEVA" },
  { name: "城际快递", code: "CJKD" },
  { name: "长通物流", code: "CTWL" },
  { name: "CNPEX中邮快递", code: "CNPEX" },
  { name: "COE东方快递", code: "COE" },
  { name: "长沙创一", code: "CSCY" },
  { name: "成都善途速运", code: "CDSTKY" },
  { name: "加拿大邮政", code: "CA" },
  { name: "能装能送", code: "CANHOLD" },
  { name: "卢森堡航空", code: "CARGOLUX" },
  { name: "广州信邦", code: "CBLLOGISTICS" },
  { name: "钏博物流", code: "CBO56" },
  { name: "中集冷云", code: "CCCC58" },
  { name: "中迅三方", code: "CD3FWL" },
  { name: "捷祥物流", code: "CDJX56" },
  { name: "鑫宸物流", code: "CDXINCHEN56" },
  { name: "银雁专送", code: "CFSS" },
  { name: "河北橙配", code: "CHENGPEI" },
  { name: "城通物流", code: "CHENGTONG" },
  { name: "荣通国际", code: "CHINAQINGGUAN" },
  { name: "SQK国际速递", code: "CHINASQK" },
  { name: "嘉荣物流", code: "CHLLOG" },
  { name: "CHS中环国际快递", code: "CHSZHONGHUANGUOJI" },
  { name: "诚和通", code: "CHT361" },
  { name: "中国香港骏辉物流", code: "CHUNFAI" },
  { name: "城市映急", code: "CITY56" },
  { name: "大韩通运", code: "CJKOREAEXPRESS" },
  { name: "城晓国际快递", code: "CKEEX" },
  { name: "出口易", code: "CKY" },
  { name: "澳通华人物流", code: "CLLEXPRESS" },
  { name: "群航国际物流", code: "CLOUDLOGISTICS365" },
  { name: "CNAIR", code: "CNAIR" },
  { name: "中澳速递", code: "CNAUSU" },
  { name: "马珂博逻", code: "CNMCPL" },
  { name: "速舟物流", code: "CNSPEEDSTER" },
  { name: "中国翼", code: "CNWS" },
  { name: "华中快递", code: "CPSAIR" },
  { name: "重庆星程快递", code: "CQXINGCHENG" },
  { name: "环旅快运", code: "CROSSBOX" },
  { name: "新时速物流", code: "CSXSS" },
  { name: "村通快递", code: "CUNTO" },
  { name: "小飞侠速递", code: "CYXFX" },
  { name: "云南诚中物流", code: "CZWLYN" },
  { name: "联合运通", code: "CTG" },
  { name: "CBO钏博物流", code: "CBO" },
  { name: "佳吉快运", code: "CNEX" },
  { name: "畅顺通达", code: "CSTD" },
  { name: "D速物流", code: "DSWL" },
  { name: "到了港", code: "DLG" },
  { name: "大田物流", code: "DTWL" },
  { name: "大众佐川急便", code: "DAZHONG" },
  { name: "叮当同城", code: "DDOTBASE" },
  { name: "多道物流", code: "DDWL" },
  { name: "深圳德创物流", code: "DECHUANGWULIU" },
  { name: "德豪驿", code: "DEHAOYI" },
  { name: "德坤物流", code: "DEKUN" },
  { name: "澳行快递", code: "DESWORKS" },
  { name: "东风全球速递", code: "DFGLOBALEX" },
  { name: "达发物流", code: "DFWL" },
  { name: "递五方云仓", code: "DI5PLL" },
  { name: "云南滇驿物流", code: "DIANYI" },
  { name: "递达速运", code: "DIDASUYUN" },
  { name: "叮咚澳洲转运", code: "DINDON" },
  { name: "叮咚快递", code: "DINGDONG" },
  { name: "递四方澳洲", code: "DISIFANGAU" },
  { name: "递四方美国", code: "DISIFANGUS" },
  { name: "吉布提", code: "DJIBOUTI" },
  { name: "东瀚物流", code: "DONGHANWL" },
  { name: "DPD", code: "DPD" },
  { name: "老司机国际快递", code: "DRIVERFASTGO" },
  { name: "德淘邦", code: "DT8ANG" },
  { name: "德邦快运/德邦物流", code: "DBLKY" },
  { name: "大马鹿", code: "DML" },
  { name: "丹鸟物流", code: "DNWL" },
  { name: "东方汇", code: "EST365" },
  { name: "递易家", code: "DYJ" },
  { name: "E特快", code: "ETK" },
  { name: "东方航空物流", code: "EALCEAIR" },
  { name: "东西E全运", code: "ECOTRANSITE" },
  { name: "易联通达", code: "EL56" },
  { name: "澳州顺风快递", code: "EMMS" },
  { name: "EMS包裹", code: "EMSBG" },
  { name: "EMS物流", code: "EMSWULIU" },
  { name: "贰仟家物流", code: "ERQIANJIA56" },
  { name: "europeanecom", code: "EUROPEANECOM" },
  { name: "可可树美中速运", code: "EXCOCOTREE" },
  { name: "7号速递", code: "EXPRESS7TH" },
  { name: "易转运", code: "EZHUANYUAN" },
  { name: "EMS国内", code: "EMS2" },
  { name: "EWE", code: "EWE" },
  { name: "E通速递", code: "ETONG" },
  { name: "飞康达", code: "FKD" },
  { name: "凡宇货的", code: "FYKD" },
  { name: "速派快递", code: "FASTGO" },
  { name: "丰程物流", code: "FCWL" },
  { name: "FEDEX联邦（国内）", code: "FEDEX" },
  { name: "飞快达", code: "FEIKUAIDA" },
  { name: "凤凰快递", code: "FENGHUANGKUAIDI" },
  { name: "奉天物流", code: "FENGTIANEXPRESS" },
  { name: "四方格", code: "FOURPXUS" },
  { name: "全速快递", code: "FSEXP" },
  { name: "富吉速运", code: "FUJISUYUN" },
  { name: "法翔速运", code: "FX" },
  { name: "飞豹快递", code: "FBKD" },
  { name: "泛球物流", code: "FANQIU" },
  { name: "丰巢", code: "FBOX" },
  { name: "飞狐快递", code: "FHKD" },
  { name: "复融供应链", code: "FRGYL" },
  { name: "飞远配送", code: "FYPS" },
  { name: "凡宇速递", code: "FYSD" },
  { name: "丰通快运", code: "FT" },
  { name: "冠达", code: "GD" },
  { name: "广东邮政", code: "GDEMS" },
  { name: "共速达", code: "GSD" },
  { name: "快捷快物流", code: "GDKJK56" },
  { name: "全网物流", code: "GDQWWL" },
  { name: "容智快运", code: "GDRZ58" },
  { name: "国际邮政包裹", code: "GJYZBG" },
  { name: "时安达速递", code: "GOEX" },
  { name: "万通快递", code: "GSWTKD" },
  { name: "冠泰", code: "GT" },
  { name: "GTS快递（广通速递）", code: "GTS" },
  { name: "广东通路", code: "GUANGDONGTONGLU" },
  { name: "永邦快递", code: "GUANGDONGYONGBANG" },
  { name: "全联速运", code: "GUEXP" },
  { name: "天天快物流", code: "GUOERYUE" },
  { name: "广州安能聚创物流", code: "GZANJCWL" },
  { name: "贵州星程快递", code: "GZXINGCHENG" },
  { name: "广通", code: "GTONG" },
  { name: "冠达快递", code: "GDKD" },
  { name: "广通速递", code: "GTKD" },
  { name: "高铁快运", code: "GTKY" },
  { name: "迦递快递", code: "GAI" },
  { name: "港快速递", code: "GKSD" },
  { name: "高铁速递", code: "GTSD" },
  { name: "广东易代收", code: "GDYDS" },
  { name: "黑狗冷链", code: "HGLL" },
  { name: "恒路物流", code: "HLWL" },
  { name: "天地华宇", code: "HOAU" },
  { name: "鸿桥供应链", code: "HOTSCM" },
  { name: "海派通物流公司", code: "HPTEX" },
  { name: "华强物流", code: "hq568" },
  { name: "华夏龙物流", code: "HXLWL" },
  { name: "河北建华", code: "HBJH" },
  { name: "汇达快递", code: "HDKD" },
  { name: "汇丰物流", code: "HF" },
  { name: "华航快递", code: "HHKD" },
  { name: "华翰物流", code: "HHWL" },
  { name: "海盟速递", code: "HMSD" },
  { name: "华企快运", code: "HQKY" },
  { name: "华兴物流", code: "HXWL" },
  { name: "昊盛物流", code: "HSWL" },
  { name: "鸿泰物流", code: "HTWL" },
  { name: "合肥汇文", code: "HFHW" },
  { name: "辉隆物流", code: "HLONGWL" },
  { name: "天津宏利德物流", code: "HLD" },
  { name: "海红网送", code: "HAIHONGWANGSONG" },
  { name: "航宇快递", code: "HANGYU" },
  { name: "豪翔物流", code: "HAOXIANGWULIU" },
  { name: "开心快递", code: "HAPPYLINK" },
  { name: "宏递快运", code: "HDWL" },
  { name: "黑猫速运", code: "HEIMAO56" },
  { name: "合心速递", code: "HEXINEXPRESS" },
  { name: "环国运物流", code: "HGY56" },
  { name: "华瀚快递", code: "HHAIR56" },
  { name: "海欣斯快递", code: "HIGHSINCE" },
  { name: "Hi淘易快递", code: "HITAOE" },
  { name: "猴急送物流", code: "HJS" },
  { name: "飞豹速递", code: "HKEEX" },
  { name: "香港邮政", code: "HKPOST" },
  { name: "互联快运", code: "HLKYTJ" },
  { name: "共联配", code: "HLPGYL" },
  { name: "海联快递", code: "HLTOP" },
  { name: "顺时达物流", code: "HNSSD56" },
  { name: "中强物流", code: "HNZQWL" },
  { name: "如家国际快递", code: "HOMECOURIER" },
  { name: "居家通", code: "HOMEXPRESS" },
  { name: "洪都拉斯", code: "HONDURAS" },
  { name: "宏捷国际物流", code: "HONGJIE" },
  { name: "宏品物流", code: "HONGPINWULIU" },
  { name: "海硕高铁速递", code: "HSGTSD" },
  { name: "户尚冷链物流", code: "HSLL" },
  { name: "恒通快递", code: "HTKD" },
  { name: "环东物流", code: "HUANDONGLG" },
  { name: "华夏货运", code: "HUAXIAHUOYUN" },
  { name: "汇峰物流", code: "HUIF56" },
  { name: "汇霖大货网", code: "HUILIN56" },
  { name: "货拉拉物流", code: "HUOLALAWULIU" },
  { name: "户通物流", code: "HUTONGWULIU" },
  { name: "鸿远物流", code: "HYESHIP" },
  { name: "上海昊宏国际货物", code: "HYK" },
  { name: "恒宇运通", code: "HYYTES" },
  { name: "华企快递", code: "HQKD" },
  { name: "韩润物流", code: "HRWL" },
  { name: "货运皇物流", code: "HYH" },
  { name: "好来运快递", code: "HLYSD" },
  { name: "皇家物流", code: "HJWL" },
  { name: "海信物流", code: "HISENSE" },
  { name: "汇森速运", code: "HSSY" },
  { name: "徽托邦物流", code: "HTB56" },
  { name: "爱拜物流", code: "IBUY8" },
  { name: "泛太优达", code: "IEX" },
  { name: "无限速递", code: "IGCAEXPRESS" },
  { name: "捷安达", code: "JAD" },
  { name: "京广速递", code: "JGSD" },
  { name: "九曳供应链", code: "JIUYE" },
  { name: "急先达", code: "JXD" },
  { name: "晋越快递", code: "JYKD" },
  { name: "佳成国际", code: "JCEX" },
  { name: "嘉诚速达", code: "JCSUDA" },
  { name: "急递", code: "JDPPLUS" },
  { name: "捷仕", code: "JETSTAREXP" },
  { name: "佳辰国际速递", code: "JIACHENEXPRESS" },
  { name: "佳家通货运", code: "JIAJIATONG56" },
  { name: "加佳物流", code: "JIAJIAWL" },
  { name: "佳吉快递", code: "JIAJIKUAIDI" },
  { name: "嘉贤物流", code: "JIAXIANWULIU_HEZUO" },
  { name: "捷邦物流", code: "JIEBORNE" },
  { name: "极光转运", code: "JIGUANG" },
  { name: "金岸物流", code: "JINAN" },
  { name: "锦程物流", code: "JINCHENGWULIU" },
  { name: "近端", code: "JINDUAN" },
  { name: "景顺物流", code: "JSWL" },
  { name: "劲通快递", code: "JINTONGKD" },
  { name: "冀速物流", code: "JISU" },
  { name: "久久物流", code: "JIUJIUWL" },
  { name: "佳捷翔物流", code: "JJX888" },
  { name: "极速达", code: "JSDKY" },
  { name: "绝配国际速递", code: "JPKD" },
  { name: "金润荷役物流", code: "JRHYWL" },
  { name: "骏绅物流", code: "JSEXPRESS" },
  { name: "时达通", code: "JSSDT56" },
  { name: "聚鼎物流", code: "JUDING" },
  { name: "聚盟共建", code: "JUMSTC" },
  { name: "骏丰国际速递", code: "JUNFENGGUOJI" },
  { name: "聚物物流", code: "JUWU" },
  { name: "捷特快递", code: "JTKD" },
  { name: "精英速运", code: "JYSY" },
  { name: "加运美", code: "JYM" },
  { name: "景光物流", code: "JGWL" },
  { name: "佳怡物流", code: "JYWL" },
  { name: "京东快运", code: "JDKY" },
  { name: "金大物流", code: "JDWL" },
  { name: "跨越速运", code: "KYSY" },
  { name: "快服务", code: "KFW" },
  { name: "快速递物流", code: "KSDWL" },
  { name: "康力物流", code: "KLWL" },
  { name: "快淘快递", code: "KTKD" },
  { name: "考拉国际速递", code: "KAOLAEXPRESS" },
  { name: "科捷物流", code: "KEJIE" },
  { name: "嘉里大荣物流", code: "KERRYTJ" },
  { name: "启邦国际物流", code: "KEYPON" },
  { name: "科紫物流", code: "KZWL" },
  { name: "快航飞递", code: "KHFD" },
  { name: "考拉速递", code: "KOALAEXP" },
  { name: "韩国邮政韩文", code: "KOREAPOSTKR" },
  { name: "淘韩国际快递", code: "KRTAO" },
  { name: "四川快优达速递", code: "KUAIYOUDA" },
  { name: "凯信达", code: "KXDA" },
  { name: "快优达速递", code: "KYDSD" },
  { name: "快8速运", code: "KBSY" },
  { name: "龙邦快递", code: "LB" },
  { name: "蓝弧快递", code: "LHKD" },
  { name: "拉火速运", code: "LAHUOEX" },
  { name: "蓝镖快递", code: "LANBIAOKUAIDI" },
  { name: "立白宝凯物流", code: "LBBK" },
  { name: "两点之间", code: "LDZY168" },
  { name: "楽道物流", code: "LEDAOWULIU" },
  { name: "乐递供应链", code: "LEDII" },
  { name: "云豹国际货运", code: "LEOPARD" },
  { name: "美联快递", code: "LETSEML" },
  { name: "联合速递", code: "LHEXPRESSUS" },
  { name: "联合快递", code: "LHKDS" },
  { name: "联邦快递-英文", code: "LIANBANGKUAIDIEN" },
  { name: "成都立即送", code: "LIJISONG" },
  { name: "领送送", code: "LINGSONG" },
  { name: "小熊物流", code: "LITTLEBEARBEAR" },
  { name: "新易泰", code: "LNET" },
  { name: "龙邦速递", code: "LONGBANWULIU" },
  { name: "加拿大龙行速运", code: "LONGCPS" },
  { name: "长风物流", code: "LONGVAST" },
  { name: "6LS EXPRESS", code: "LSEXPRESS" },
  { name: "乐天速递", code: "LTEXP" },
  { name: "联通快递", code: "LTPARCEL" },
  { name: "陆本速递", code: "LUBEN" },
  { name: "论道国际物流", code: "LUNDAO" },
  { name: "绿卡城配", code: "LVKAR" },
  { name: "联运通物流", code: "LYT" },
  { name: "乐捷递", code: "LJD" },
  { name: "立即送", code: "LJS" },
  { name: "联昊通速递", code: "LHT" },
  { name: "民邦快递", code: "MB" },
  { name: "民航快递", code: "MHKD" },
  { name: "美快", code: "MK" },
  { name: "门对门快递", code: "MDM" },
  { name: "今枫国际快运", code: "MAPLEEXPRESS" },
  { name: "迈达物流", code: "MD" },
  { name: "美泰物流", code: "MEITAI" },
  { name: "美西快递", code: "MEIXI" },
  { name: "魔速达", code: "MOSUDA" },
  { name: "闽盛快递", code: "MSKD" },
  { name: "迈隆递运", code: "MRDY" },
  { name: "明亮物流", code: "MLWL" },
  { name: "美乐维冷链物流", code: "MEILEWEI" },
  { name: "南方传媒物流", code: "NFCM" },
  { name: "星云速递", code: "NEBUEX" },
  { name: "尼尔物流", code: "NEWL" },
  { name: "速尔哪吒", code: "NEZHA" },
  { name: "云链航空?", code: "NHACEH" },
  { name: "南天物流", code: "NT56" },
  { name: "腾达速递", code: "NNTENGDA" },
  { name: "诺尔国际物流", code: "NUOER" },
  { name: "偌亚奥国际快递", code: "NUOYAAO" },
  { name: "新西兰中通", code: "NZZTO" },
  { name: "能达速递", code: "NEDA" },
  { name: "ONTRAC", code: "ONTRAC" },
  { name: "平安达腾飞快递", code: "PADTF" },
  { name: "泛捷快递", code: "PANEX" },
  { name: "品骏快递", code: "PJ" },
  { name: "陪行物流", code: "PXWL" },
  { name: "诚一物流", code: "PARCELCHINA" },
  { name: "英国邮政大包EMS", code: "PARCELFORCECN" },
  { name: "急顺通", code: "PZHJST" },
  { name: "普畅物流", code: "PCWL56" },
  { name: "全球速递", code: "PDSTOW" },
  { name: "派尔快递", code: "PEEX" },
  { name: "配思货运", code: "PEISIHUOYUNKUAIDI" },
  { name: "鹏程快递", code: "PENGCHENG" },
  { name: "品信快递", code: "PINXINKUAIDI" },
  { name: "龙行天下", code: "PMT0704BE" },
  { name: "PostElbe", code: "POSTELBE" },
  { name: "荷兰邮政-中国件", code: "POSTNLCHINA" },
  { name: "PCA Express", code: "PCA" },
  { name: "皮牙子快递", code: "BAZIRIM" },
  { name: "全晨快递", code: "QCKD" },
  { name: "全日通快递", code: "QRT" },
  { name: "快客快递", code: "QUICK" },
  { name: "全信通", code: "QXT" },
  { name: "秦邦快运", code: "QBEXPRESS" },
  { name: "雪域快递", code: "QHXYKD" },
  { name: "雪域易购", code: "QHXYYG" },
  { name: "全川摩运", code: "QUANCHUAN56" },
  { name: "千里速递", code: "QIANLI" },
  { name: "秦岭智能速运", code: "QINLING" },
  { name: "全球邮政", code: "QQYZ" },
  { name: "全际通", code: "QUANJITONG" },
  { name: "全速通", code: "QUANSUTONG" },
  { name: "全通快运", code: "QUANTWL" },
  { name: "七曜中邮", code: "QYZY" },
  { name: "如风达", code: "RFD" },
  { name: "荣庆物流", code: "RQ" },
  { name: "日日顺物流", code: "RRS" },
  { name: "日昱物流", code: "RLWL" },
  { name: "人人转运", code: "RENRENEX" },
  { name: "睿和泰速运", code: "RHT" },
  { name: "锐界同城", code: "RJTCSD" },
  { name: "日日顺快线", code: "RRSKX" },
  { name: "日日顺智慧物联", code: "RRSZHWL" },
  { name: "瑞丰速递", code: "RFEX" },
  { name: "赛澳递", code: "SAD" },
  { name: "苏宁物流", code: "SNWL" },
  { name: "圣安物流", code: "SAWL" },
  { name: "上大物流", code: "SDWL" },
  { name: "盛丰物流", code: "SFWL" },
  { name: "速通物流", code: "ST" },
  { name: "速腾快递", code: "STWL" },
  { name: "速必达物流", code: "SUBIDA" },
  { name: "速递e站", code: "SDEZ" },
  { name: "速呈宅配", code: "SCZPDS" },
  { name: "速尔快递", code: "SURE" },
  { name: "山东海红", code: "SDHH" },
  { name: "盛辉物流", code: "SHWL" },
  { name: "穗佳物流", code: "SJWL" },
  { name: "三态速递", code: "STSD" },
  { name: "山西红马甲", code: "SXHMJ" },
  { name: "世运快递", code: "SYKD" },
  { name: "盛通快递", code: "STKD" },
  { name: "郑州速捷", code: "SJ" },
  { name: "赛澳递for买卖宝", code: "SAIAODIMMB" },
  { name: "叁虎物流", code: "SANHUWULIU" },
  { name: "中加国际快递", code: "SCIC" },
  { name: "四川星程快递", code: "SCXINGCHENG" },
  { name: "药淘齐物流", code: "SCYTQ" },
  { name: "速达速递", code: "SDSD" },
  { name: "尚橙物流", code: "SHANGCHENG" },
  { name: "上海快通", code: "SHANGHAIKUAITONG" },
  { name: "山西建华", code: "SHANXIJIANHUA" },
  { name: "捎客物流", code: "SHAOKE" },
  { name: "杰响物流", code: "SHBWCH" },
  { name: "闪货极速达", code: "SHJSD" },
  { name: "上海林道货运", code: "SHLDHY" },
  { name: "同城快寄", code: "SHPOST" },
  { name: "顺丰-繁体", code: "SHUNFENGHK" },
  { name: "顺丰快运", code: "SHUNFENGKUAIYUN" },
  { name: "顺丰冷链", code: "SHUNFENGLENGYUN" },
  { name: "顺捷达", code: "SHUNJIEDA" },
  { name: "顺捷丰达", code: "SHUNJIEFENGDA" },
  { name: "顺士达速运", code: "SHUNSHID" },
  { name: "签收快递", code: "SIGNEDEXPRESS" },
  { name: "中外运空运", code: "SINOAIRINEX" },
  { name: "中外运速递-中文", code: "SINOEX" },
  { name: "易普递", code: "SIXROAD" },
  { name: "四季安物流", code: "SJA56" },
  { name: "行必达", code: "SPEEDA" },
  { name: "申必达", code: "SPEEDOEX" },
  { name: "速速达", code: "SSD" },
  { name: "星速递", code: "STAREX" },
  { name: "星运快递", code: "STARYVR" },
  { name: "美国申通", code: "STOEXPRESS" },
  { name: "申通新西兰", code: "STONEWZEALAND" },
  { name: "智德物流", code: "STZD56" },
  { name: "速豹", code: "SUBAOEX" },
  { name: "特急便物流", code: "SUCMJ" },
  { name: "速风快递", code: "SUFENGKUAIDI" },
  { name: "速品快递", code: "SUPINEXPRESS" },
  { name: "苏里南", code: "SURPOST" },
  { name: "瑞士邮政", code: "SWCH" },
  { name: "瑞典邮政", code: "SWEDENPOST" },
  { name: "三象速递", code: "SXEXPRESS" },
  { name: "红马甲物流", code: "SXHONGMAJIA" },
  { name: "沈阳佳惠尔", code: "SYJHE" },
  { name: "深圳DPEX", code: "SZDPEX" },
  { name: "世华通物流", code: "SZSHIHUATONG56" },
  { name: "深圳邮政", code: "SZYOUZHENG" },
  { name: "顺心捷达", code: "SX" },
  { name: "商桥物流", code: "SQWL" },
  { name: "佳旺达物流", code: "SYJWDX" },
  { name: "三志物流", code: "SANZHI" },
  { name: "台湾邮政", code: "TAIWANYZ" },
  { name: "泰联物流?", code: "HNTLWL" },
  { name: "唐山申通", code: "TSSTO" },
  { name: "特急送", code: "TJS" },
  { name: "通和天下", code: "TONGHETIANXIA" },
  { name: "通用物流", code: "TYWL" },
  { name: "泰进物流", code: "TAIJIN" },
  { name: "特宝专送", code: "TBZS" },
  { name: "天翔快递", code: "TIANXIANG" },
  { name: "万家通快递", code: "TIMEDG" },
  { name: "泰实货运", code: "TJKJWL" },
  { name: "老扬州物流", code: "TJLYZ56" },
  { name: "明通国际快递", code: "TNJEX" },
  { name: "通达兴物流", code: "TONGDAXING" },
  { name: "运联科技", code: "TU" },
  { name: "铁中快运", code: "TZKY" },
  { name: "华宇物流", code: "TDHY" },
  { name: "天玺物流", code: "TXWL" },
  { name: "泰捷达物流", code: "TJDGJWL" },
  { name: "优联吉运", code: "ULUCKEX" },
  { name: "UTAO 优到", code: "UTAOSCM" },
  { name: "全一快递", code: "UAPEX" },
  { name: "万家康", code: "WJK" },
  { name: "万家物流", code: "WJWL" },
  { name: "中粮我买网", code: "WM" },
  { name: "万象物流", code: "WXWL" },
  { name: "微特派", code: "WTP" },
  { name: "宁夏万家通", code: "WANJIATONG" },
  { name: "万达美", code: "WDM" },
  { name: "威盛快递", code: "WHEREXPESS" },
  { name: "凡仕特物流", code: "WLFAST" },
  { name: "沃埃家", code: "WOWVIP" },
  { name: "伍圆速递", code: "WUYUANSUDI" },
  { name: "51跨境通", code: "WYKJT" },
  { name: "温通物流", code: "WTWL" },
  { name: "武汉晓毕物流", code: "WHXBWL" },
  { name: "迅驰物流", code: "XCWL" },
  { name: "信丰物流", code: "XFEX" },
  { name: "希优特", code: "XYT" },
  { name: "祥龙运通", code: "XLYT" },
  { name: "新杰物流", code: "XJ" },
  { name: "鑫梦成", code: "XINMENGCHENG" },
  { name: "新宁物流", code: "XINNING" },
  { name: "鑫通宝物流", code: "XTB" },
  { name: "国晶物流", code: "XDSHIPPING" },
  { name: "祥龙运通物流", code: "XIANGLONGYUNTONG" },
  { name: "翔腾物流", code: "XIANGTENG" },
  { name: "喜来快递", code: "XLKD" },
  { name: "迅选物流", code: "XUNXUAN" },
  { name: "行云物流", code: "XYB2B" },
  { name: "鑫远东速运", code: "XYD666" },
  { name: "西邮寄", code: "XYJ" },
  { name: "晓毕物流", code: "XIAOBI" },
  { name: "源安达快递", code: "YAD" },
  { name: "远成物流", code: "YCWL" },
  { name: "远成快运", code: "YCSY" },
  { name: "义达国际物流", code: "YDH" },
  { name: "药康达快递", code: "YKD" },
  { name: "原飞航物流", code: "YFHEX" },
  { name: "耀奇物流", code: "YAOQI" },
  { name: "亿领速运", code: "YILINGSUYUN" },
  { name: "亿顺航", code: "YISHUNHANG" },
  { name: "易通达", code: "YITONGDA" },
  { name: "鼹鼠快送", code: "YSEXPRESS" },
  { name: "运通快运", code: "YTKY168" },
  { name: "亚风快递", code: "YFSD" },
  { name: "运通快递", code: "YTKD" },
  { name: "亿翔快递", code: "YXKD" },
  { name: "运东西网", code: "YUNDX" },
  { name: "壹米滴答", code: "YMDD" },
  { name: "一站通速运", code: "YZTSY" },
  { name: "驭丰速运", code: "YFSUYUN" },
  { name: "余氏东风", code: "YSDF" },
  { name: "耀飞快递", code: "YF" },
  { name: "韵达快运", code: "YDKY" },
  { name: "云路", code: "YL" },
  { name: "邮必佳", code: "YBJ" },
  { name: "越丰物流", code: "YFEX" },
  { name: "顺捷丰达/银捷速递", code: "YJSD" },
  { name: "英脉物流", code: "YMWL" },
  { name: "音素快运", code: "YSKY" },
  { name: "一统飞鸿", code: "YTFH" },
  { name: "亚马逊中国", code: "YAMAXUNWULIU" },
  { name: "一辉物流", code: "YATFAI" },
  { name: "易达丰国际速递", code: "YDFEXPRESS" },
  { name: "易航物流", code: "YIHANGMALL" },
  { name: "英超物流", code: "YINGCHAO" },
  { name: "一起送", code: "YIQISONG" },
  { name: "一正达速运", code: "YIZHENGDASUYUN" },
  { name: "武汉优进汇", code: "YJHGO" },
  { name: "洋口岸", code: "YKOUAN" },
  { name: "黑猫同城送", code: "YNZTSY" },
  { name: "永邦国际物流", code: "YONGBANGWULIU" },
  { name: "永昌物流", code: "YONGCHANG" },
  { name: "邮必佳快递", code: "YOUBIJIA" },
  { name: "邮畅快运", code: "YOUCWL" },
  { name: "邮来速递", code: "YOULAI" },
  { name: "壹品速递", code: "YPSD" },
  { name: "远盾物流", code: "YUANDUN" },
  { name: "圆通快运", code: "YUANTONGKUAIYUN" },
  { name: "元智捷诚", code: "YUANZHIJIECHENG" },
  { name: "宇捷通", code: "YUJTONG" },
  { name: "美国云达", code: "YUNDAEXUS" },
  { name: "韵丰物流", code: "YUNFENG56" },
  { name: "运通速运", code: "YUNTONG" },
  { name: "邮驿帮速运", code: "YYBSY" },
  { name: "西安运逸快递", code: "YYEXP" },
  { name: "远洋国际快递", code: "YYEXPRESS" },
  { name: "鹰运", code: "YYSDCN" },
  { name: "圆通国际", code: "YTOGJ" },
  { name: "宇鑫物流", code: "YXWL" },
  { name: "包裹/平邮/挂号信", code: "YZGN" },
  { name: "一智通", code: "YZT" },
  { name: "一路发物流", code: "YLFWL" },
  { name: "云聚物流", code: "YJWL" },
  { name: "宇佳物流", code: "YUJIAWL" },
  { name: "众邮快递", code: "ZYE" },
  { name: "中铁快运", code: "ZTKY" },
  { name: "中天万运", code: "ZHONGTIANWANYUN" },
  { name: "中外运速递", code: "ZWYSD" },
  { name: "澳转运", code: "ZY_AZY" },
  { name: "八达网", code: "ZY_BDA" },
  { name: "贝易购", code: "ZY_BYECO" },
  { name: "赤兔马转运", code: "ZY_CTM" },
  { name: "浩运物流", code: "ZBHY56" },
  { name: "逐电快运", code: "ZHUDIANKUAIYUN" },
  { name: "卓实快运", code: "ZHUOSHIKUAIYUN" },
  { name: "CUL中美速递", code: "ZY_CUL" },
  { name: "ETD", code: "ZY_ETD" },
  { name: "风驰快递", code: "ZY_FCKD" },
  { name: "风雷速递", code: "ZY_FLSD" },
  { name: "皓晨优递", code: "ZY_HCYD" },
  { name: "海带宝", code: "ZY_HDB" },
  { name: "汇丰美中速递", code: "ZY_HFMZ" },
  { name: "豪杰速递", code: "ZY_HJSD" },
  { name: "华美快递", code: "ZY_HMKD" },
  { name: "360hitao转运", code: "ZY_HTAO" },
  { name: "海淘村", code: "ZY_HTCUN" },
  { name: "365海淘客", code: "ZY_HTKE" },
  { name: "华通快运", code: "ZY_HTONG" },
  { name: "海星桥快递", code: "ZY_HXKD" },
  { name: "华兴速运", code: "ZY_HXSY" },
  { name: "LogisticsY", code: "ZY_IHERB" },
  { name: "领跑者快递", code: "ZY_LPZ" },
  { name: "量子物流", code: "ZY_LZWL" },
  { name: "明邦转运", code: "ZY_MBZY" },
  { name: "168 美中快递", code: "ZY_MZ" },
  { name: "欧e捷", code: "ZY_OEJ" },
  { name: "欧洲疯", code: "ZY_OZF" },
  { name: "欧洲GO", code: "ZY_OZGO" },
  { name: "全美通", code: "ZY_QMT" },
  { name: "直德邮", code: "ZDEPOST" },
  { name: "三三国际物流", code: "ZENZEN" },
  { name: "招金精炼", code: "ZHAOJIN" },
  { name: "鑫正一快递", code: "ZHENGYIKUAIDI" },
  { name: "中宏物流", code: "ZHONGHONGWL" },
  { name: "中环转运", code: "ZHONGHUANUS" },
  { name: "中速快件", code: "ZHONGSUKUAIDI" },
  { name: "中铁飞豹", code: "ZHONGTIEWULIU" },
  { name: "忠信达", code: "ZHONGXINDA" },
  { name: "众派速递", code: "ZHPEX" },
  { name: "创运物流", code: "ZJCY56" },
  { name: "振捷国际货运", code: "ZJGJ56" },
  { name: "苏通快运", code: "ZJSTKY" },
  { name: "三真驿道", code: "ZLINK" },
  { name: "中粮鲜到家物流", code: "ZLXDJWL" },
  { name: "中通智运", code: "ZTOZY" },
  { name: "中融泰隆", code: "ZRTL" },
  { name: "准实快运", code: "ZSKY" },
  { name: "明辉物流", code: "ZSMHWL" },
  { name: "中途速递", code: "ZTCCE" },
  { name: "纵通速运", code: "ZTSY" },
  { name: "中网物流", code: "ZWWL" },
  { name: "爱购转运", code: "ZY_AG" },
  { name: "澳世速递", code: "ZY_AUSE" },
  { name: "斑马物流", code: "ZY_BM" },
  { name: "百通物流", code: "ZY_BT" },
  { name: "策马速递", code: "ZY_CM" },
  { name: "宜送转运", code: "ZY_ESONG" },
  { name: "飞碟快递", code: "ZY_FD" },
  { name: "飞鸽快递", code: "ZY_FG" },
  { name: "风行快递", code: "ZY_FX" },
  { name: "皓晨快递", code: "ZY_HC" },
  { name: "君安快递", code: "ZY_JA" },
  { name: "骏达快递", code: "ZY_JD" },
  { name: "久禾快运", code: "ZY_JH" },
  { name: "金海淘", code: "ZY_JHT" },
  { name: "龙象快递", code: "ZY_LX" },
  { name: "美速通", code: "ZY_MST" },
  { name: "QQ-EX", code: "ZY_QQEX" },
  { name: "瑞天快递", code: "ZY_RT" },
  { name: "四方转运", code: "ZY_SFZY" },
  { name: "上腾快递", code: "ZY_ST" },
  { name: "滕牛快递", code: "ZY_TN" },
  { name: "唐三藏转运", code: "ZY_TSZ" },
  { name: "同心快递", code: "ZY_TX" },
  { name: "天翼快递", code: "ZY_TY" },
  { name: "星辰快递", code: "ZY_XC" },
  { name: "先锋快递", code: "ZY_XF" },
  { name: "云骑快递", code: "ZY_YQ" },
  { name: "运淘美国", code: "ZY_YTUSA" },
  { name: "中远快运", code: "ZY100" },
  { name: "增速海淘", code: "ZYZOOM" },
  { name: "郑州建华", code: "ZZJH" },
  { name: "SCS国际物流", code: "ZY_SCS" },
  { name: "SOHO苏豪国际", code: "ZY_SOHO" },
  { name: "Sonic-Ex速递", code: "ZY_SONIC" },
  { name: "通诚美中快递", code: "ZY_TCM" },
  { name: "TrakPak", code: "ZY_TPAK" },
  { name: "天天海淘", code: "ZY_TTHT" },
  { name: "天泽快递", code: "ZY_TZKD" },
  { name: "迅达快递", code: "ZY_XDKD" },
  { name: "信达速运", code: "ZY_XDSY" },
  { name: "新干线快递", code: "ZY_XGX" },
  { name: "信捷转运", code: "ZY_XJ" },
  { name: "优购快递", code: "ZY_YGKD" },
  { name: "友家速递(UCS)", code: "ZY_YJSD" },
  { name: "云畔网", code: "ZY_YPW" },
  { name: "易送网", code: "ZY_YSW" },
  { name: "中运全速", code: "ZYQS" },
  { name: "中邮物流", code: "ZYWL" },
  { name: "汇强快递", code: "ZHQKD" },
  { name: "众通快递", code: "ZTE" },
  { name: "中通快运", code: "ZTOKY" },
  { name: "中通冷链", code: "ZTOCC" },
  { name: "中骅物流", code: "ZHWL" },
  { name: "中铁物流", code: "ZTWL" },
  { name: "智汇鸟", code: "ZHN" },
  { name: "中原快运", code: "ZYKY" },
];


export const autoRefreshTime = [
  {value:'10分钟',type:''},
  {value:'30分钟',type:''},
  {value:'1小时',type:''},
  {value:'2小时',}
]

export const autoCancelTime = [
  {value:'24小时'},
  {value:'48小时'},
  {value:'一周'}
]



/*
{
    "status": 1,
    "info": "成功获取",
    "cbId": "callback_hBJbIZmS",
    "data": {
        "orders": [
            {
                "id": "284939356394",
                "dealtime": "2023-11-03 10:18:27",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "飞兹(fizz)特氟龙多功能剪刀组合装美工刀+剪刀二合一办公家用生活裁剪两用不锈钢办公学生文具 红色 FZ21213",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥16.99在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284939356394&PassKey=CD4C7699223ABAFA43BB58C1209D4C43",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "283256084637",
                "dealtime": "2023-11-01 23:02:56",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "海康威视（HIKVISION）1TB Type-C USB3.2超极速固态U盘S560移动固态闪存优盘  双接口手机电脑通用便携",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥389.00在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=283256084637&PassKey=485725988372402157964ECF752681D1",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "284689401607",
                "dealtime": "2023-10-31 20:00:15",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "京东京造Z9 Smart人体工学椅 电竞椅 办公椅子电脑椅久坐 双背撑腰 带脚踏",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥678.99在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284689401607&PassKey=5C861C92D09491350307F9D3D838230B",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "283128502301",
                "dealtime": "2023-10-31 13:54:33",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "新日（Sunra）新日折叠电动车 【10补邮费专用】勿单拍，拍前联系客服！！ 10",
                        "num": "x6",
                        "consignee": "陈一枭",
                        "amount": "¥59.99在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=283128502301&PassKey=D983C648FAD4854762516949145AFAF0",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "283090371710",
                "dealtime": "2023-10-30 12:17:58",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "木藝生显示器增高架台式电脑支架显示屏高底座桌面置物架键盘架子储物架 【收纳伴侣套装】双层-颜色备注 置物架",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥45.03在线支付",
                        "detailUrl": ""
                    },
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "木藝生嗮家装嗮视频赠多重好礼 详询客服 1",
                        "num": "x1",
                        "consignee": "",
                        "amount": "",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=283090371710&PassKey=5D29EB66834913CE86DFA90DA6D0187B",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "284595370625",
                "dealtime": "2023-10-30 08:48:21",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "绿巨能（llano） USB/Type-C读卡器3.0高速SD/TF卡多功能合一单反相机佳能手机iPad行车记录仪监控存储内存卡",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥41.98在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284595370625&PassKey=7450A3A738BFF51F5574984C747DED88",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "283133167728",
                "status": "已完成"
            },
            {
                "id": "284571865829",
                "dealtime": "2023-10-29 15:31:26",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "Oftensee 平板电脑支架iPadminiPro桌面懒人手机金属调节折叠便携通用学习绘画支撑托架 【360°旋转升降】铝合金折叠支架-灰色",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥57.20在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284571865829&PassKey=EB2AB89662363AC54B3BE4367D88DB2E",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "284505543916",
                "status": "已完成"
            },
            {
                "id": "284557315586",
                "dealtime": "2023-10-29 15:31:26",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "达摩鲨 K3PRO 三模无线小键盘 蓝牙2.4G 19键机械数字键盘 RGB全键热插拔自定义财务键盘",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥192.00在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284557315586&PassKey=51AB2B6692AD263E1AD45176A4BCBFF8",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "284505543916",
                "status": "已完成"
            },
            {
                "id": "284503744837",
                "dealtime": "2023-10-28 10:22:52",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥1459.00在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284503744837&PassKey=70946DB028B132FEC9DB25095F9A8C7A",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已取消"
            },
            {
                "id": "283032384561",
                "dealtime": "2023-10-27 00:28:37",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "bestoct头戴式手机支架gopro12固定拍摄支架第一人称视角随身直播穿戴身上配件路亚户外夹子 手机/GoPro运动相机头戴支架【旗舰版】",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥34.88在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=283032384561&PassKey=F9E0E91F6BD1C40DFCCEAD31FB98DA5B",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "282969861055",
                "dealtime": "2023-10-26 17:42:03",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "闪迪（SanDisk）A2 512GB TF（MicroSD）存储卡 V30 U3 4K至尊超极速移动版内存卡 读速200MB/s 写速140MB/s",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥478.98在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282969861055&PassKey=4F2869A6E54C4B30027BF8ADC9D3ABB9",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "284361162979",
                "dealtime": "2023-10-25 21:32:13",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "大疆 DJI Osmo Pocket 3 全能套装 一英寸口袋云台相机 OP灵眸手持数码相机 旅游vlog 便携美颜摄像",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥4499.00在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284361162979&PassKey=227E2F6A6110187781D313B889F2909F",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "284298131403",
                "dealtime": "2023-10-24 18:58:13",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "建材再保1年",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥0.00在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284298131403&PassKey=78F34CA71640DF9DFEEEEC058365715C",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "284226831790",
                "dealtime": "2023-10-24 16:35:01",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "罗技（G）G502 X LIGHTSPEED无线游戏鼠标 进阶无线版 全新光学-机械混合微动 HERO引擎 电竞鼠标 白色",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥548.98在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=284226831790&PassKey=05F04FAA6EF1DBE4CB196BE02577209F",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "282916217232",
                "dealtime": "2023-10-24 12:29:56",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "米家追光氛围灯带电竞RGB小米追光 PC智能联动 声光互动氛围灯",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥198.99在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282916217232&PassKey=F729D077E47481C0FAA247A1AAF74319",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "282915951344",
                "dealtime": "2023-10-24 12:25:02",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "鸥歌电竞房洞洞板置物架万能挂板电脑桌面壁挂式铁艺墙上洞洞板收纳 【带边框带挂钩】180*100 黑色",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥141.35在线支付",
                        "detailUrl": ""
                    },
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "鸥歌电竞房洞洞板置物架万能挂板电脑桌面壁挂式铁艺墙上洞洞板收纳 加购收藏 黑色",
                        "num": "x1",
                        "consignee": "",
                        "amount": "",
                        "detailUrl": ""
                    },
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "鸥歌电竞房洞洞板置物架万能挂板电脑桌面壁挂式铁艺墙上洞洞板收纳 商品自带挂钩10个，勿拍 黑色",
                        "num": "x1",
                        "consignee": "",
                        "amount": "",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282915951344&PassKey=96F3BAA6AB8501C0189FAD20B9139A38",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "282763769589",
                "dealtime": "2023-10-24 08:02:43",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "机械师KT68 机械键盘 无线/2.4G/蓝牙三模游戏键盘 笔记本电脑键盘 智慧屏 黑金版 知秋轴",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥698.98在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282763769589&PassKey=79DB94CCB6BFFE48020D317AACF424B0",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            },
            {
                "id": "282531547616",
                "dealtime": "2023-10-13 11:09:46",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "banq&JOY联名款 64GB TF（MicroSD）存储卡U3 C10 A1 V30 4K 高速款 行车记录仪&监控摄像头手机内存卡",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥16.90在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282531547616&PassKey=F3115E8FA32E2185A93B2B7EC636F24D",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "282541777638",
                "status": "已完成"
            },
            {
                "id": "282531547584",
                "dealtime": "2023-10-13 11:09:46",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "闪迪（SanDisk）32GB SD存储卡 C10 至尊高速版内存卡 读速120MB/s 捕捉全高清 数码相机理想伴侣",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥35.88在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=282531547584&PassKey=66B067AF79455BE828831D9FE0BDB0D6",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "282541777638",
                "status": "已完成"
            },
            {
                "id": "277161423519",
                "dealtime": "2023-10-09 09:48:45",
                "items": [
                    {
                        "cover": "https://misc.360buyimg.com/lib/img/e/blank.gif",
                        "name": "胖牛40cm小型摄影棚器材美食珠宝拍摄补光灯PU5040A白光单色温led摄影棚摄影柔光箱送6色背景纸影棚器材套装",
                        "num": "x1",
                        "consignee": "陈一枭",
                        "amount": "¥135.99在线支付",
                        "detailUrl": ""
                    }
                ],
                "detailUrl": "https://details.jd.com/normal/item.action?orderid=277161423519&PassKey=DB6D6826BEE91A92F531774FF2728F37",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "已完成"
            }
        ],
        "parentOrders": [
            {
                "id": "283133167728",
                "dealtime": "2023-10-30 08:48:21",
                "items": [],
                "detailUrl": "https:undefined",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "订单状态：已拆分"
            },
            {
                "id": "284505543916",
                "dealtime": "2023-10-29 15:31:26",
                "items": [],
                "detailUrl": "https:undefined",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "订单状态：已拆分"
            },
            {
                "id": "282541777638",
                "dealtime": "2023-10-13 11:09:46",
                "items": [],
                "detailUrl": "https:undefined",
                "arrivalAt": "",
                "latestNodes": [],
                "expressType": "",
                "expressNo": "",
                "parentOrderId": "",
                "status": "订单状态：已拆分"
            }
        ]
    }
}


**/ 