export const iconList = [
  { icon: "message" },
  { icon: "star" },
  { icon: "smile" },
  { icon: "shezhi1" },
  { icon: "aixin" },
  { icon: "yanjing" },
  {
    icon: "",
  },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
  { icon: "" },
];
